# Use Node.js LTS image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and install production deps
COPY package*.json ./
RUN npm install --production

# Copy the rest of the app
COPY . .

# App Engine expects container to listen on PORT env var
EXPOSE 8080

# Start the app
CMD [ "npm", "start" ]